services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
    volumes:
      - pdf_to_podcast_gradio:/app/.gradio
      - pdf_to_podcast_gradio_examples:/app/gradio_cached_examples
      - pdf_to_podcast_gradio_files:/app/gradio_cached_files

volumes:
  pdf_to_podcast_gradio:
  pdf_to_podcast_gradio_examples:
  pdf_to_podcast_gradio_files:
